services:
  postgres:
    image: postgres:17
    container_name: arduino-iot-postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/migrations:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: arduino-iot-backend

    restart: unless-stopped

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      SIMULATOR_INTERNAL_URL: http://simulator:4000
      SIMULATOR_CONTROL_TOKEN: ${SIMULATOR_CONTROL_TOKEN:-local-development-simulator-token}

    ports:
      - "3000:3000"

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: arduino-iot-frontend

    restart: unless-stopped

    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_SOCKET_URL: ${VITE_SOCKET_URL}

    ports:
      - "5173:5173"

    depends_on:
      backend:
        condition: service_started

  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile

    container_name: arduino-iot-simulator

    restart: unless-stopped

    environment:
      SIMULATOR_BACKEND_INTERNAL_URL: http://backend:3000
      SIMULATOR_CONTROL_TOKEN: ${SIMULATOR_CONTROL_TOKEN:-local-development-simulator-token}
      SIMULATOR_CONTROL_PORT: 4000

    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data: